### ISSUE TITLE
Unable to get images to load

### ISSUE THREAD

**Issue by oyeanuj** [Merri/react-lazy#13]
Hey @Merri, sorry for a generic subject line but I've been unable to get `react-lazy` to function with my setup. Essentially, when the page loads, the images are not loaded. If I resize the window, or call `checkElementsInViewport` (in `componentDidMount`), then the images load but unfortunately, all of the images load (as opposed to only those in viewport) :/

Here is my code:
```jsx
<div className = {styles.imageGroup} >
  <Lazy onLoad = {this.handleWrapperLoad}>
   {this.renderImages()}
  </Lazy>
</div>

```

```css
.imageGroup {
	border: 1px solid purple;
	min-height: 600px;
	width: 100%;
	display: flex;
	flex-wrap: wrap;
}

/* imageWrapper is just container for each image */
@media screen and (min-width: 600px) {
  .imageWrapper {
    width: calc(50% - 2rem);
  }
}

@media screen and (min-width: 1000px) {
  .imageWrapper {
    width: calc(33.3333% - 2rem);
  }
}
```

Here is what the component looks like in Devtools:
<img width="763" alt="screen shot 2017-07-22 at 3 15 34 pm" src="https://user-images.githubusercontent.com/9633371/28494926-3aa85b9a-6ef2-11e7-8f5d-9ed53aeb7845.png">

---
I also tried using `proto-img` branch but ran into the following JS errors:
<img width="601" alt="screen shot 2017-07-22 at 3 05 26 pm" src="https://user-images.githubusercontent.com/9633371/28494931-576112cc-6ef2-11e7-9368-0d9f25bdc523.png">

---

I imagine I am doing something simple wrong, so any tips are much appreciated :)
